version: '3'

services:
  app_file_service:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    env_file: 
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app_file_service